services:
  nginx:
    image: nginx:latest
    container_name: itsd-nginx
    ports:
      - "8080:80"
    volumes:
      - itsd-nginx-data:/usr/share/nginx/html
    networks:
      - itsd-network

  postgres:
    image: postgres:16
    container_name: itsd-postgres
    environment:
      POSTGRES_USER: itsd
      POSTGRES_PASSWORD: itsd123
      POSTGRES_DB: itsd_db
    volumes:
      - itsd-postgres-data:/var/lib/postgresql/data
    networks:
      - itsd-network

volumes:
  itsd-nginx-data:
    external: true

  itsd-postgres-data:

networks:
  itsd-network:
    external: true